import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Calendar, CheckCircle2, ChevronRight, Clock3, Home, Layers3, Menu, PackageCheck, Plus, Search, Shirt, X, AlertTriangle, ClipboardList, Truck, ScanLine} from 'lucide-react';
import './styles.css';

const stages=['Requested','Picked Up','Tagged','In Batch','Washing','Drying','Ironing','Ready','Delivered'];
const disputeStages=['Reported','Under Investigation','Investigation Complete','Resolution Offered','Resolved','Rejected'];
const uid=(prefix)=>`${prefix}-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
const seed={
 student:{name:'Aarav Sharma',hostel:'Maple Residence',room:'B-214'},
 requests:[
  {id:'LDR-2026-0082',items:[{id:'i1',name:'Blue denim shirt',category:'Shirt',quantity:2,color:'Blue',brand:'Levi’s',instructions:'Cold wash only',tag:'TAG-82A'},{id:'i2',name:'Black joggers',category:'Bottom wear',quantity:1,color:'Black',brand:'',instructions:'',tag:'TAG-82B'}],pickupDate:'Sep 21, 2026',pickupTime:'6:00 – 7:00 PM',status:'Washing',expected:'Today, 8:30 PM',batch:'BAT-0921-A',created:'Sep 20, 2026',history:[['Requested','Sep 20, 4:12 PM'],['Picked Up','Sep 21, 6:25 PM'],['Tagged','Sep 21, 6:42 PM'],['In Batch','Sep 21, 7:00 PM'],['Washing','Sep 21, 7:15 PM']]},
  {id:'LDR-2026-0071',items:[{id:'i3',name:'White bed sheet',category:'Linen',quantity:1,color:'White',brand:'',instructions:'',tag:'TAG-71A'}],pickupDate:'Sep 18, 2026',pickupTime:'5:00 – 6:00 PM',status:'Ready',expected:'Ready now',batch:'BAT-0919-B',created:'Sep 18, 2026',history:[['Requested','Sep 18, 10:05 AM'],['Picked Up','Sep 18, 5:45 PM'],['Washing','Sep 19, 8:30 AM'],['Ready','Sep 19, 3:15 PM']]},
  {id:'LDR-2026-0065',items:[{id:'i4',name:'College hoodie',category:'Outerwear',quantity:1,color:'Grey',brand:'Nike',instructions:'',tag:'TAG-65A'}],pickupDate:'Sep 13, 2026',pickupTime:'6:00 – 7:00 PM',status:'Delivered',expected:'Delivered Sep 15',batch:'BAT-0915-A',created:'Sep 13, 2026',history:[['Requested','Sep 13, 2:18 PM'],['Delivered','Sep 15, 7:02 PM']]}
 ],
 batches:[{id:'BAT-0921-A',status:'Washing',expected:'Today, 8:30 PM',requests:['LDR-2026-0082'],created:'Today, 7:00 PM'}, {id:'BAT-0919-B',status:'Ready',expected:'Ready now',requests:['LDR-2026-0071'],created:'Sep 19, 8:00 AM'}],
 disputes:[{id:'DSP-2026-0014',requestId:'LDR-2026-0065',item:'College hoodie',type:'Stained item',description:'A small stain remains near the sleeve.',status:'Under Investigation',created:'Sep 16, 2026',notes:'Quality team is checking wash records.',resolution:''}]
};
const load=()=>JSON.parse(localStorage.getItem('laundry-roulette')||'null')||seed;
const Status=({value})=><span className={`badge ${value.toLowerCase().replaceAll(' ','-')}`}>{value}</span>;
const formatItems=(req)=>req.items.reduce((n,i)=>n+i.quantity,0);
function App(){
 const [data,setData]=useState(load), [role,setRole]=useState('student'), [page,setPage]=useState('dashboard'), [selected,setSelected]=useState(null), [modal,setModal]=useState(null), [menu,setMenu]=useState(false), [query,setQuery]=useState('');
 useEffect(()=>localStorage.setItem('laundry-roulette',JSON.stringify(data)),[data]);
 const requests=data.requests, current=selected&&requests.find(r=>r.id===selected);
 const stats=useMemo(()=>({total:requests.length,active:requests.filter(r=>!['Delivered','Ready'].includes(r.status)).length,ready:requests.filter(r=>r.status==='Ready').length,completed:requests.filter(r=>r.status==='Delivered').length,disputes:data.disputes.filter(d=>!['Resolved','Rejected'].includes(d.status)).length}),[data]);
 const nav=role==='student'?[['dashboard','Dashboard',Home],['new','New request',Plus],['requests','My laundry',Shirt],['disputes','Disputes',AlertTriangle]]:[['dashboard','Dashboard',Home],['requests','Requests',ClipboardList],['batches','Batches',Layers3],['processing','Processing',ScanLine],['disputes','Disputes',AlertTriangle]];
 const go=(p)=>{setPage(p);setSelected(null);setMenu(false)};
 const addRequest=(form)=>{const id=uid('LDR');const items=form.items.map((i,n)=>({...i,id:uid('ITM'),tag:`TAG-${id.slice(-4)}${String.fromCharCode(65+n)}`}));const r={id,items,pickupDate:form.pickupDate,pickupTime:form.pickupTime,status:'Requested',expected:'Within 48 hours of pickup',batch:null,created:'Just now',history:[['Requested','Just now']]};setData(d=>({...d,requests:[r,...d.requests]}));setModal(null);setSelected(id);setPage('detail')};
 const progress=(request,status)=>{let oi=stages.indexOf(request.status),ni=stages.indexOf(status); if(ni!==oi+1 && !(request.status==='Requested'&&status==='Picked Up')) return alert('Processing must move forward one stage at a time.');setData(d=>({...d,requests:d.requests.map(r=>r.id===request.id?{...r,status,expected:status==='Ready'?'Ready for pickup':status==='Delivered'?'Delivered':r.expected,history:[...r.history,[status,'Just now']]}:r),batches:d.batches.map(b=>b.requests.includes(request.id)?{...b,status}:b)}));};
 const addDispute=(f)=>{setData(d=>({...d,disputes:[{id:uid('DSP'),...f,status:'Reported',created:'Just now',notes:'',resolution:''},...d.disputes]}));setModal(null);setPage('disputes')};
 const updateDispute=(id,status)=>setData(d=>({...d,disputes:d.disputes.map(x=>x.id===id?{...x,status,notes:status==='Under Investigation'?'Investigation started by laundry team.':x.notes,resolution:status==='Resolution Offered'?'₹150 refund approved to laundry wallet.':x.resolution}:x)}));
 return <div className="app"><aside className={menu?'open':''}><div className="brand"><div className="logo"><Shirt size={21}/></div><div>Laundry Day <em>Roulette</em></div></div><div className="role-switch"><button className={role==='student'?'active':''} onClick={()=>{setRole('student');go('dashboard')}}>Student</button><button className={role==='admin'?'active':''} onClick={()=>{setRole('admin');go('dashboard')}}>Staff</button></div><nav>{nav.map(([key,label,Icon])=><button key={key} className={page===key?'current':''} onClick={()=>go(key)}><Icon size={18}/>{label}</button>)}</nav><div className="support"><div className="avatar">AS</div><div><b>{role==='student'?'Aarav Sharma':'Maya, Operator'}</b><small>{role==='student'?'B-214 · Maple':'Laundry Operations'}</small></div></div></aside><main><header><button className="mobile-menu" onClick={()=>setMenu(!menu)}><Menu/></button><div><p className="eyebrow">{role==='student'?'STUDENT PORTAL':'LAUNDRY OPERATIONS'}</p><h1>{page==='detail'?current?.id:page==='new'?'Create laundry request':page.charAt(0).toUpperCase()+page.slice(1)}</h1></div><div className="header-right"><span className="date"><Calendar size={16}/> Monday, Sep 21</span>{role==='student'&&<button className="primary" onClick={()=>go('new')}><Plus size={17}/>New request</button>}</div></header>
 {page==='dashboard'&&<Dashboard role={role} stats={stats} requests={requests} batches={data.batches} disputes={data.disputes} open={(id)=>{setSelected(id);setPage('detail')}}/>}
 {page==='new'&&<RequestForm onSave={addRequest} onCancel={()=>go('dashboard')}/>} 
 {(page==='requests'||page==='processing')&&<RequestTable requests={requests} admin={role==='admin'} query={query} setQuery={setQuery} open={(id)=>{setSelected(id);setPage('detail')}} progress={progress}/>}
 {page==='detail'&&current&&<RequestDetail request={current} admin={role==='admin'} progress={progress} back={()=>go('requests')} report={()=>setModal('dispute')}/>} 
 {page==='batches'&&<Batches batches={data.batches} requests={requests} setData={setData}/>} 
 {page==='disputes'&&<Disputes disputes={data.disputes} admin={role==='admin'} update={updateDispute} create={()=>setModal('dispute')}/>}
 </main>{modal==='dispute'&&<DisputeForm requests={requests} initial={current} onSave={addDispute} close={()=>setModal(null)}/>}</div>
}
function Dashboard({role,stats,requests,batches,disputes,open}){const cards=role==='student'?[['Total requests',stats.total,ClipboardList,'blue'],['Active laundry',stats.active,Clock3,'amber'],['Ready for pickup',stats.ready,PackageCheck,'green'],['Completed',stats.completed,CheckCircle2,'purple'],['Open disputes',stats.disputes,AlertTriangle,'red']]:[['Pending requests',stats.active,ClipboardList,'amber'],['Active batches',batches.filter(b=>b.status!=='Ready').length,Layers3,'blue'],['Processing laundry',requests.filter(r=>['Washing','Drying','Ironing'].includes(r.status)).length,Shirt,'purple'],['Ready for delivery',stats.ready,Truck,'green'],['Open disputes',stats.disputes,AlertTriangle,'red']];return <><section className="welcome"><div><span>GOOD AFTERNOON, {role==='student'?'AARAV':'MAYA'} 👋</span><h2>{role==='student'?'Your laundry, clearly in motion.':'Keep every load moving.'}</h2><p>{role==='student'?'Track your clothes from pickup to delivery.':'Monitor batches and handle exceptions in one place.'}</p></div><div className="roulette">🧺<small>Next pickup<br/><b>Today · 6 PM</b></small></div></section><section className="cards">{cards.map(([l,n,I,c])=><article className="metric" key={l}><div className={'icon '+c}><I size={20}/></div><div><small>{l}</small><strong>{n}</strong></div></article>)}</section><section className="panel"><div className="panel-head"><div><h2>{role==='student'?'Recent laundry':'Incoming & active requests'}</h2><p>Updated moments ago</p></div><button className="text-button">View all <ChevronRight size={16}/></button></div><RequestTable requests={requests.slice(0,4)} open={open} compact/></section></>}
function RequestTable({requests,admin,query='',setQuery,open,progress,compact}){let rows=requests.filter(r=>`${r.id} ${r.items.map(i=>i.name).join(' ')} ${r.batch||''}`.toLowerCase().includes(query.toLowerCase()));return <div>{!compact&&<div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search request, tag or batch…" value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{rows.length} requests</span></div>}<div className="table-wrap"><table><thead><tr><th>Request</th><th>Items</th><th>Status</th><th>Expected completion</th>{admin&&<th>Batch</th>}<th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.id}</b><small>{r.created}</small></td><td>{formatItems(r)} item{formatItems(r)!==1?'s':''}<small>{r.items[0].name}</small></td><td><Status value={r.status}/></td><td>{r.expected}</td>{admin&&<td>{r.batch||<span className="muted">Unassigned</span>}</td>}<td><button className="row-action" onClick={()=>open(r.id)}>View</button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="empty">No requests match your search.</div>}</div>}
function RequestDetail({request,admin,progress,back,report}){const currentStage=stages.indexOf(request.status); return <><button className="back" onClick={back}>← Back to requests</button><section className="detail-grid"><div><div className="panel hero-detail"><div><div><p className="eyebrow">LAUNDRY REQUEST</p><h2>{request.id}</h2><p>Pickup: {request.pickupDate} · {request.pickupTime}</p></div><Status value={request.status}/></div><div className="timeline">{stages.map((s,i)=><div key={s} className={i<=currentStage?'done':''}><i>{i<currentStage?'✓':i===currentStage?'●':'○'}</i><span>{s}</span></div>)}</div><div className="completion"><Clock3 size={18}/><div><small>Expected completion</small><b>{request.expected}</b></div></div></div><div className="panel"><div className="panel-head"><div><h2>Tagged items</h2><p>{formatItems(request)} pieces in this request</p></div></div>{request.items.map(item=><div className="item" key={item.id}><div className="item-icon"><Shirt size={21}/></div><div><b>{item.name} <span>× {item.quantity}</span></b><p>{item.category} · {item.color}{item.brand&&` · ${item.brand}`}</p>{item.instructions&&<small>“{item.instructions}”</small>}</div><code>{item.tag}</code></div>)}</div></div><div><div className="panel"><h2>Activity history</h2><div className="history">{[...request.history].reverse().map(([status,time],i)=><div key={i}><i></i><div><b>{status}</b><small>{time}</small></div></div>)}</div></div>{admin?<div className="panel action-panel"><h2>Processing controls</h2><p>Advance this request one verified stage at a time.</p>{request.status!=='Delivered'?<button className="primary full" onClick={()=>progress(request,stages[currentStage+1])}>Mark as {stages[currentStage+1]} <ChevronRight size={17}/></button>:<span className="success-line">✓ Lifecycle completed</span>}</div>:<div className="panel action-panel"><h2>Something wrong?</h2><p>Report a missing, damaged, wrong or stained item.</p><button className="secondary full" onClick={report}>Report an issue</button></div>}</div></section></>}
function RequestForm({onSave,onCancel}){const [form,setForm]=useState({pickupDate:'Sep 22, 2026',pickupTime:'6:00 – 7:00 PM',items:[{name:'',category:'Shirt',quantity:1,color:'',brand:'',instructions:''}]});const set=(key,val)=>setForm(f=>({...f,[key]:val}));const item=(n,key,val)=>setForm(f=>({...f,items:f.items.map((x,i)=>i===n?{...x,[key]:val}:x)}));const submit=e=>{e.preventDefault();if(form.items.some(x=>!x.name.trim()||!x.color.trim()))return alert('Please add an item name and color for every item.');onSave(form)};return <form className="form-layout" onSubmit={submit}><section className="panel form-main"><div className="panel-head"><div><h2>What are we washing?</h2><p>Each item receives its own trackable tag.</p></div></div>{form.items.map((x,n)=><div className="item-form" key={n}><div className="form-number">{n+1}</div><div className="fields"><label>Item name<input required value={x.name} onChange={e=>item(n,'name',e.target.value)} placeholder="e.g. Cotton t-shirt"/></label><label>Category<select value={x.category} onChange={e=>item(n,'category',e.target.value)}><option>Shirt</option><option>Bottom wear</option><option>Outerwear</option><option>Linen</option><option>Other</option></select></label><label>Quantity<input type="number" min="1" max="10" value={x.quantity} onChange={e=>item(n,'quantity',+e.target.value)}/></label><label>Color<input required value={x.color} onChange={e=>item(n,'color',e.target.value)} placeholder="e.g. Navy blue"/></label><label>Brand <span>optional</span><input value={x.brand} onChange={e=>item(n,'brand',e.target.value)} placeholder="e.g. Nike"/></label><label className="wide">Special instructions <span>optional</span><input value={x.instructions} onChange={e=>item(n,'instructions',e.target.value)} placeholder="e.g. Wash separately, no bleach"/></label></div>{form.items.length>1&&<button type="button" className="remove" onClick={()=>setForm(f=>({...f,items:f.items.filter((_,i)=>i!==n)}))}>Remove</button>}</div>)}<button type="button" className="add-item" onClick={()=>setForm(f=>({...f,items:[...f.items,{name:'',category:'Shirt',quantity:1,color:'',brand:'',instructions:''}]}))}><Plus size={17}/> Add another item</button></section><aside className="panel collection"><h2>Collection details</h2><label>Hostel / block<input value="Maple Residence" disabled/></label><label>Room number<input value="B-214" disabled/></label><label>Pickup date<input value={form.pickupDate} onChange={e=>set('pickupDate',e.target.value)}/></label><label>Preferred pickup time<select value={form.pickupTime} onChange={e=>set('pickupTime',e.target.value)}><option>6:00 – 7:00 PM</option><option>7:00 – 8:00 PM</option><option>8:00 – 9:00 PM</option></select></label><div className="form-actions"><button className="primary full" type="submit">Submit request <ChevronRight size={17}/></button><button className="cancel" type="button" onClick={onCancel}>Cancel</button></div></aside></form>}
function Batches({batches,requests,setData}){const [open,setOpen]=useState(null);const create=()=>{let eligible=requests.filter(r=>!r.batch&&r.status==='Requested');if(!eligible.length)return alert('No unassigned requests are available.');let id=uid('BAT');setData(d=>({...d,batches:[{id,status:'Picked Up',expected:'Tomorrow, 6:00 PM',requests:eligible.map(x=>x.id),created:'Just now'},...d.batches],requests:d.requests.map(r=>eligible.some(x=>x.id===r.id)?{...r,batch:id,status:'Picked Up',history:[...r.history,['Picked Up','Just now']]}:r)}));};return <section className="panel"><div className="panel-head"><div><h2>Laundry batches</h2><p>Group requests to process them together.</p></div><button className="primary" onClick={create}><Plus size={17}/>Create batch</button></div><div className="batch-grid">{batches.map(b=><article className="batch-card" key={b.id}><div><span className="batch-icon"><Layers3 size={19}/></span><Status value={b.status}/></div><h3>{b.id}</h3><p>{b.requests.length} requests · {b.requests.reduce((x,id)=>x+(requests.find(r=>r.id===id)?.items.length||0),0)} item groups</p><div><small>Expected completion</small><b>{b.expected}</b></div><button className="secondary full" onClick={()=>setOpen(open===b.id?null:b.id)}>{open===b.id?'Hide details':'View batch'}</button>{open===b.id&&<ul>{b.requests.map(id=><li key={id}>{id}</li>)}</ul>}</article>)}</div></section>}
function Disputes({disputes,admin,update,create}){return <section className="panel"><div className="panel-head"><div><h2>{admin?'Dispute resolution center':'Your reported issues'}</h2><p>{disputes.filter(x=>!['Resolved','Rejected'].includes(x.status)).length} open cases need attention</p></div>{!admin&&<button className="primary" onClick={create}><Plus size={17}/>Report issue</button>}</div><div className="dispute-list">{disputes.map(d=><article className="dispute" key={d.id}><div className="dispute-symbol"><AlertTriangle size={20}/></div><div className="dispute-copy"><div><b>{d.type}</b><Status value={d.status}/></div><p>{d.id} · {d.requestId} · {d.item}</p><small>{d.description}</small>{d.notes&&<div className="note">Investigation: {d.notes}</div>}{d.resolution&&<div className="resolution">Resolution: {d.resolution}</div>}</div>{admin&&!['Resolved','Rejected'].includes(d.status)&&<div className="dispute-actions"><select value={d.status} onChange={e=>update(d.id,e.target.value)}>{disputeStages.map(s=><option key={s}>{s}</option>)}</select><button className="primary" onClick={()=>update(d.id,'Resolved')}>Close case</button></div>}</article>)}</div>{!disputes.length&&<div className="empty">No disputes have been reported.</div>}</section>}
function DisputeForm({requests,initial,onSave,close}){const [f,setF]=useState({requestId:initial?.id||requests[0]?.id||'',item:initial?.items[0]?.name||'',type:'Missing item',description:''});const req=requests.find(r=>r.id===f.requestId);useEffect(()=>{if(req)setF(x=>({...x,item:req.items[0]?.name||''}))},[f.requestId]);return <div className="modal-backdrop"><form className="modal" onSubmit={e=>{e.preventDefault();if(!f.description.trim())return alert('Please describe the issue.');onSave(f)}}><button type="button" className="close" onClick={close}><X/></button><p className="eyebrow">DISPUTE & RESOLUTION</p><h2>Report an issue</h2><p className="modal-lead">We’ll match this to the tagged item and start an investigation.</p><label>Laundry request<select value={f.requestId} onChange={e=>setF({...f,requestId:e.target.value})}>{requests.map(r=><option key={r.id}>{r.id}</option>)}</select></label><label>Item<select value={f.item} onChange={e=>setF({...f,item:e.target.value})}>{req?.items.map(i=><option key={i.id}>{i.name}</option>)}</select></label><label>Problem type<select value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{['Missing item','Damaged item','Wrong item returned','Stained item','Other issue'].map(x=><option key={x}>{x}</option>)}</select></label><label>What happened?<textarea required value={f.description} onChange={e=>setF({...f,description:e.target.value})} placeholder="Tell us what you noticed…"/></label><div className="evidence">+ Add photo evidence <span>Optional</span></div><button className="primary full">Submit report <ChevronRight size={17}/></button></form></div>}
createRoot(document.getElementById('root')).render(<App/>);
